# -*- coding: utf-8 -*-
"""Guessing game one.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cn2q7r6RpuNO4_FOXbJkyWSCkd7zoh4u
"""

import random

def guessing_game():

  lower_bound = 1
  upper_bound = 100
  secreat_number = random.randint(lower_bound, upper_bound)
  attemp = 0
  guess = 0

  while guess != secreat_number:
    guess = int(input("Guess a random number between 1 and 100 : "))
    attemp += 1
    if guess < secreat_number:
      print("Too low")
    elif guess > secreat_number:
      print("Too high")

  print("You guessed the number in {} attempts".format(attemp))

if __name__ == "__main__":
  guessing_game()



