# -*- coding: utf-8 -*-
"""python 30 days series.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jayLkyuw-v8vF9Ae2D6mRYMFB1unHOBQ
"""



"""## Python : Day 1

Day 1: Introduction & Setup - Variables, print(), comments
"""



"""## Python : Day 2

Data Types - int, float, str, bool, type conversion

🧠 Insights:

"5" * 3 results in '555' because string × int = string repeated.


bool("False") is True because the string is non-empty.


int("10.5") causes an error, but float("10.5") works.
"""

# examples

# 1.

a = "5"
b = 3
print(a * b)

x = bool("False")
print(x)

num = 3.999
print(int(num))

print(bool(0.0))
print(bool("0"))

val = "123abc"
print(int(val))

s = "10"
f = float(s)
i = int(f)
print(type(i), i)

x = "True"
print(bool(x))

a = "7"
b = 2
result = int(a) / b
print(result)

value = str(bool(int("0")))
print(value, type(value))

print(int(" 123 "))

a = '7'
b = '3'
print(a * b)

print(bool("0"))  # What will it print?

a = int("5") + float("3.2")
print(a)

int("abc")



"""## Python day : 3

Day 3: Operators - Arithmetic, comparison, logical, bitwise

✅ Arithmetic
✅ Comparison
✅ Logical
✅ Bitwise

## Practice questions
"""

print(4 // 3 + 4 % 3)

a = 7
b = 3
print(a & b, a | b, a ^ b)

print(True + False * True)

x = 10
x = x >> 2
print(x)

print(2 ** 3 ** 2)

print(10 > 5 and 3 < 1 or not False)

print((4 < 5) and (5 < 6) and not (6 < 7))

a = 12
b = 5
print((a & b) << 1)

print(~(3 & 1))

print(5 < 6 < 7)    # vs
print((5 < 6) < 7)



"""## 📘 Day 4: Strings — Slicing, Methods, Formatting

✅ String slicing
✅ Common string methods
✅ String formatting
✅ Then end with 10 hard practice questions (no solutions)
"""

s = "Python"
print(s[0])     # P
print(s[-1])    # n
print(s[1:4])   # yth
print(s[:])     # full string
print(s[::-1])  # reverse

s = "abracadabra"
print(s[2:7:2])

s = "a b c d e"
print("-".join(s.split()))

text = "  Learn Python FAST  "
print(text.strip().replace(" ", "_").upper())

s = "abc123ABC"
print(s.isalpha(), s.isalnum())

# Given a string s = "hello world", reverse only the word order.

s = 'hello world'
word = (' '.join(s.split()[::-1]))
print(word)

#Write a one-liner that removes all vowels from the string "Artificial Intelligence".

s = 'Artificial Intelligence'
r = ''.join([i for i in s if i.lower() not in 'aeiou'])
print(r)

#Given s = "abcd", print the string repeated 4 times but without using * operator.
s = 'abcd'
for i in range(4):
  for j in s:
    print(''.join(j))

s = "ABCDabcd1234"
print(s[::2] + s[::-3])

s = "Data Science"
print(f"{s:^20}")

s = "PyTHon is AwEsOMe"
print(s.swapcase().count("o"))

"""## Day 5 : Lists - Indexing, slicing, methods, list comprehension

A list in Python is an ordered, mutable collection of elements.

You can store different data types in a list (integers, strings, floats, even other lists).

So, when you add a new item it will be saved at the end of the list.

You can change, add, or remove elements after creation.

#When NOT to Use Lists

❌ If you only need unique values → use set.

❌ If you need key-value pairs → use dict.

❌ If data should be unchangeable → use tuple.

# To add value and element in list

1. Append - Adds an element at the end of the list
2. insert - Adds an element at the specified position
3. extend - Add the elements of a list (or any iterable), to the end of the current list
"""

# Insert
fruits = ['apple', 'banana', 'cherry']

fruits.insert(1, "orange")
print(fruits)

# extend
fruits = ['apple', 'banana', 'cherry']

points = (1, 4, 5, 9)

fruits.extend(points)
print(fruits)

"""# To delete an element from list

1. remove - Removes the item with the specified value
2. pop - Removes the element at the specified position
3. clear - Removes all the elements from the list
"""

# remove
fruits = ['apple', 'banana', 'cherry']

fruits.remove("banana")
print(fruits)

# pop
fruits = ['apple', 'banana', 'cherry']

fruits.pop(1)
print(fruits)

"""# Questions"""

#1 Create a list of 10 integers. Print: The first element.The last element.The third element from the end.

lies = [1,2,3,4,5,6,7,8,9,10]
print(lies[0])
print(lies[-1])
print(lies[-3])

#2 Given a list of names, print the name at index 2 and index -3.

names = ['Alice', 'Bob', 'Charlie', 'David', 'Eve']
print(names[2])
print(names[-3])

#3 Given list1 = [5, 10, 15, 20, 25], print: First 3 elements. Last 2 elements. Every alternate element.

list1 = [5, 10, 15, 20, 25]
print(list1[:3])
print(list1[-2:])
print(list1[::2])

list2 = [5, 10, 15, 20, 25]
print(list2[0:3])
print(list2[-2:])
print(list2[0:5:2])

""" If you want to use [-1:-3] then you must include negative step as indexing is always goes in +1 step so, [-1:-3:-1]"""

#4 Write a program to copy a list using slicing and prove that changing one does not change the other

original_list = [1, 2, 3, 4, 5]
copied_list = original_list[:]

print("Original List:", original_list)
print("Copied List:", copied_list)

#5. Given a list of integers, remove all occurrences of 3.
#  We can not use remove because remove only deletes first occurance not multiple occurance.
#l1 = [1,2,3,5,3,6,7]
#l1.remove(3)
#print(l1)

l1 = [1,2,3,5,3,6,7]
l1 = [i for i in l1 if i != 3]
print(l1)

#6 Given a list of numbers, find the index of the first occurrence of 7.
l1 = [1,2,3,7,4,5]
print(l1.index(7))

#7 Write a program to sort a list of strings in reverse alphabetical order without using sorted() functio
l1 = ['apple','banana','cherry','grapes','guava']
l1.sort(reverse=True)
print(l1)

#9 Given a list [1, 2, 3, 4, 5], use slicing to: Reverse the list. Extract only the middle three numbers.

l1 = [1,2,3,4,5]
print(l1[::-1])
print(l1[1:4])

# Write a program that counts how many times "apple" appears in a given list.

fruits = ['apple', 'banana', 'apple', 'cherry', 'apple']
count = fruits.count('apple')
print(count)

"""## Structure for List Comprehension

[Expression for item in iterable if condition]

# If - else structure

In a list comprehension, there are two different kinds of if:

Filter if (at the end):
[expr for item in iterable if condition]

Conditional Expression (if–else) (inside expression)
[expr_if_true if condition else expr_if_false for item in iterable]
"""

for i in range(1,21):
  i = i**2
  #print(i)

l = [i**2 for i in range(1,21)]
print(l)

a = [1,2,3,4,5]
l = [i for i in a if i%2==0]
print(l)

# Given a list of words, create a new list containing only words with more than 4 letters.

a = ['apple','banana','wer','t','rrrrrr']
l = [i for i in a if len(i)>4]
print(l)

# Create a list of all odd numbers between 50 and 100.
a = [i for i in range(50,101) if i%2 != 0]
print(a)

# Given sentence = "Python is powerful and fun", create a list of lengths of each word.
sentence = "Python is powerful and fun"
l = [len(i) for i in sentence.split()]
print(l)

# Use list comprehension to flatten it into:
matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
a = [j for i in matrix for j in i]
print(a)

a = [1,2,3]
b = [4,5,6]

l = [(x,y) for x in a for y in b]
print(l)

# Use list comprehension to extract the diagonal [1, 5, 9].
matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

l = [matrix[i][i] for i in range(len(matrix))]
print(l)

sentence = "Python is really powerful and fun"

l = [i[::-1] if len(i)>3 else i for i in sentence.split()]
print(l)

"""## Day 6 : Tuples & Sets

## Tuples

Ordered → maintains the sequence of items.

Immutable → cannot change after creation (no append, remove, etc.).

Allows duplicates.

Can hold different data types.

Indexing & slicing works like lists.

Basic Operations

Access: t[0], t[-1]

Slicing: t[1:3]

Concatenation: t1 + t2

Repetition: t * 3

Membership: x in t

Methods: .count(), .index()

## Set

A set is an unordered, mutable collection of unique elements.

Unordered → no indexing, order is not guaranteed.

Unique elements only.

Mutable → you can add/remove items.
"""

# Create a tuple with 5 elements and access the 2nd and 4th element.

a = ('apple',3,'banana',6,4)
print(a[1])
print(a[3])

# Try modifying a tuple element — what happens?

a = ('apple',3,'banana',6,4)
a[0] ='cherry'
print(a)

# Count how many times "apple" appears in a tuple.

a = ('apple',3,'banana',6,4,'apple')
print(a.count('apple'))

# Add an element to a set and then remove it.

a = {1,2,3,4,5}

a.add(6)
print(a)

a.remove(6)
print(a)

# Concatenate two tuples (1, 2, 3) and (4, 5, 6).

a = (1,2,3)
b = (4,5,6)
print(a+b)

# Given two sets, find:

#Elements common to both.

#Elements in the first but not in the second.

# Elements present in either set but not both.

a = {1,2,3,4,5}
b = {4,5,6,7,8}

print(a.intersection(b))
print(a.difference(b))
print(a.symmetric_difference(b))

# Write a program to check if two sets are disjoint.

a = {1,2,3,4,5}
b = {4,5,6,7,8}

print(a.isdisjoint(b))

# Use set comprehension to get all vowels from a given string.

s = {'e','g','a','h'}
a = [i for i in s if i in ('a','e','i','o','u')]
print(a)

# Create a tuple of 3 nested tuples and access an element inside the inner tuple.

a = ((1,2,3),(4,5,6),(7,8,9))
print(a[1][1])

# Write a function that returns multiple values using a tuple.

# Given a list of words, remove duplicates using a set.

a = ['apple','banana','cherry','banana']
b = set(a)
print(b)

# Use a frozen set as a key in a dictionary.

a = {1,2,3,4,5}
b = frozenset(a)
print(b)

# Implement symmetric difference between two sets without using ^.

"""## Day 7 :  Dictionaries - Keys/values, methods, looping"""

#Given the dictionary car = {"brand": "Toyota", "model": "Camry", "year": 2020}, access and print only the "brand" value.

car = {"brand": "Toyota", "model": "Camry", "year": 2020}
print(car['brand'])

# Add a new key "color" with value "red" to the car dictionary from Question 2. Print the updated dictionary.

car = {"brand": "Toyota", "model": "Camry", "year": 2020}
car['color'] = 'Red'
print(car)

#Create an empty dictionary called scores and add three student names as keys with their test scores as values.
#Use any names and scores you want.
scores = {}
scores['Alice'] = 80
scores['Bob'] = 40
scores['Charl'] = 30
print(scores)

#Given student = {"name": "John", "grade": 85}, change John's grade to 92 and print the dictionary.
student = {"name": "John", "grade": 85}
student['grade'] = 92
print(student)

#Write code to loop through this dictionary and print each key-value pair:
colors = {"red": "#FF0000", "green": "#00FF00", "blue": "#0000FF"}

for key,value in colors.items():
  print(key,value)

#Create a dictionary inventory = {"apples": 50, "bananas": 30, "oranges": 25}. Write code to:

#Print all fruit names (keys)
#Print all quantities (values)
#Print the total quantity of all fruits

inventory = {"apples": 50, "bananas": 30, "oranges": 25}
print(inventory.keys())
print(inventory.values())
print(sum(inventory.values()))

#Given temperatures = {"Monday": 72, "Tuesday": 68, "Wednesday": 75, "Thursday": 70}, find and print the day with the highest temperature.
temperatures = {"Monday": 72, "Tuesday": 68, "Wednesday": 75, "Thursday": 70}
print(max(temperatures, key=temperatures.get))

#Create a dictionary where keys are numbers 1 to 5 and values are their squares (1:1, 2:4, 3:9, etc.). Use a loop to create this dictionary.

d = {}
for i in range(1,6):
  d[i] = i**2
print(d)

#Write a program that counts how many times each word appears in this sentence: "the quick brown fox jumps over the lazy dog the fox". Store results in a dictionary.

sentence = "the quick brown fox jumps over the lazy dog the fox"
d = {}
for i in sentence.split():
  if i in d:
    d[i] += 1
  else:
    d[i] = 1
print(d)

#Given two dictionaries:
#dict1 = {"a": 1, "b": 2, "c": 3}
#dict2 = {"d": 4, "e": 5, "f": 6}
#Combine them into a single dictionary and print it.

dict1 = {"a": 1, "b": 2, "c": 3}
dict2 = {"d": 4, "e": 5, "f": 6}
dict1.update(dict2)
print(dict1)

#Create a dictionary phonebook = {"Alice": "555-1234", "Bob": "555-5678", "Charlie": "555-9012"}. Write code to:

#Check if "Alice" exists in the phonebook
#Safely get "David's" number (he's not in the phonebook)
#Remove "Bob" from the phonebook

#phonebook = {"Alice": "555-1234", "Bob": "555-5678", "Charlie": "555-9012"}
phonebook = {"Alice": "555-1234", "Bob": "555-5678", "Charlie": "555-9012"}
print('Alice' in phonebook)
print(phonebook.get('David','Not in phonebook'))
phonebook.pop('Bob')
print(phonebook)

#reate a nested dictionary representing a simple school with 2 classes. Each class should have a teacher name and a list of 3 students with their grades. Print the average grade for each class.

School = {"Math Class" : {"Teacher" : 'Mr James',
                          "Students" : {'Alice' : 85,
                                        'Bob' : 78,
                                        'Charles' : 56}},
          "Science Class" : {'Teacher' : 'Mr qqq',
                             "Students" : {'a' : 78,
                                           'b' : 34,
                                           'c' : 89}}
}
print(School)

for class_name, class_info in School.items():
    print(f"\n📚 {class_name}")
    print(f"👨‍🏫 Teacher: {class_info['Teacher']}")
    print("👥 Students:")

    total_grades = 0
    student_count = 0
    for student, grade in class_info['Students'].items():
        print(f"  {student}: {grade}")
        total_grades += grade
        student_count += 1

    average_grade = total_grades / student_count
    print(f"📈 Average Grade: {average_grade:.2f}")

#Write a program that takes a string and creates a dictionary showing the position(s) where each character appears. For example, "hello" → {"h": [0], "e": [1], "l": [2, 3], "o": [4]}

string = "hello"
d = {}
for i in range(len(string)):
  if string[i] in d:
    d[string[i]].append(i)
  else:
    d[string[i]] = [i]
print(d)

#Given this list of dictionaries representing products:
#pythonproducts = [
#    {"name": "laptop", "price": 1000, "category": "electronics"},
 #   {"name": "chair", "price": 150, "category": "furniture"},
  #  {"name": "phone", "price": 800, "category": "electronics"},
   # {"name": "desk", "price": 300, "category": "furniture"}]
#Group them by category and calculate the average price for each category.

products = [
    {"name": "laptop", "price": 1000, "category": "electronics"},
    {"name": "chair", "price": 150, "category": "furniture"},
    {"name": "phone", "price": 800, "category": "electronics"},
    {"name": "desk", "price": 300, "category": "furniture"}
]

# Group prices by category
category_prices = {}

for product in products:
    category = product["category"]
    price = product["price"]

    if category not in category_prices:
        category_prices[category] = []

    category_prices[category].append(price)

# Calculate averages
for category, prices in category_prices.items():
    average = sum(prices) / len(prices)
    print(f"{category}: Average price = ${average:.2f}")

Grade_book = {'Alice':{'Science':38,
                       'Maths':67,
                       'Drawing':89},
              'Bob':{'Science':89,
                     'Maths':89,
                     'Drawing':45},
              'Charles':{'Science':89,
                         'Maths':67,
                         'Drawing':56}}

for student_name, subjects in Grade_book.items():
  print(f"\n{student_name}")
  print(f"Science: {subjects['Science']}")
  print(f"Maths: {subjects['Maths']}")
  print(f"Drawing: {subjects['Drawing']}")

#Calculate and display each student's overall average and each subject's class average.
student_averages = {}

for student_name, subjects in Grade_book.items():
  grade = subjects.values()
  grades_list = list(grade)

  total_points = sum(grade)
  number_of_subjects = len(grade)
  average = total_points / number_of_subjects
  print(average)

  student_averages[student_name] = average

  print(f"\n{student_name}:")
  print(f"  Grades: {grades_list}")
  print(f"  Total Points: {total_points}")
  print(f"  Number of Subjects: {number_of_subjects}")
  print(f"  Overall Average: {average:.1f}")

subject_grades = {
    'Science': [],
    'Maths': [],
    'Drawing': []
}

for student_name, subjects in Grade_book.items():
  for subject, grade in subjects.items():
    subject_grades[subject].append(grade)

subject_averages = {}

for subject_name, grades in subject_grades.items():
    total_points = sum(grades)
    number_of_students = len(grades)
    average = total_points / number_of_students

    subject_averages[subject_name] = average

    print(f"\n{subject_name}:")
    print(f"  All student grades: {grades}")
    print(f"  Total points: {total_points}")
    print(f"  Number of students: {number_of_students}")
    print(f"  Class Average: {average:.1f}")

"""# Day 8: if, else, elif - Conditional Logic

Conditional logic allows you to control the flow of your program based on whether a condition is True or False.
In Python, we use:

if → to check a condition

elif (else if) → to check additional conditions if the previous ones were false

else → to run when none of the above conditions are true
"""

# Easy problems

#1. Create a program that determines if a person is eligible to vote (age >= 18).

age = int(input("Enter age:"))
if age >= 18:
  print("Eligible to vote")
else:
  print("Not eligible to vote")

# Write a program that checks if a year is a leap year (divisible by 4).

year = int(input("Enter year:"))
if year % 4 == 0:
  print("Leap year")
else:
  print("Not a leap year")

#Make a program that compares two numbers and prints which one is larger.

a = int(input("Enter first number:"))
b = int(input("Enter second number:"))
if a > b:
  print("First number is larger")
elif a < b:
  print("Second number is larger")
else:
  print("Both numbers are equal")

#Write a program that checks if a string is empty or not.

a = input("Enter a string:")
if a == "":
  print("String is empty")
else:
  print("String is not empty")

#Write a program that calculates electricity bill with different rates for different usage slabs
# (0-100: ₹2/unit, 101-300: ₹3/unit, 301+: ₹5/unit).

number = int(input("Enter Number :"))
if number <= 100:
  print(number*2)
elif number > 100 and number <= 300:
  print(number*3)
else:
  print(number*5)

#Create a password strength checker that validates length, uppercase, lowercase, and special characters.

password = input("Enter password:")
length = len(password)
upper = 0
lower = 0
special = 0
for i in password:
  if i.isupper():
    upper += 1
  elif i.islower():
    lower += 1
  elif i.isalnum():
    special += 1
  else:
    pass
if length >= 8 and upper >= 1 and lower >= 1 and special >= 1:
  print("Valid password")
else:
  print("Invalid password")

#Write a program that determines the quadrant of a point based on x,y coordinates.

x= int(input("Enter number x :"))
y = int(input("Enter number y :"))

if x>0 and y>0:
  print("Quadrant I")
elif x<0 and y>0:
  print("Quadrant II")
elif x<0 and y<0:
  print("Quadrant III")
else:
  print("Quadrant IV")

n1 = int(input("Enter first number:"))
n2 = int(input("Enter second number:"))

choice = input("Enter choice (+,-,*,/)")
if choice == '+':
  print(n1+n2)
elif choice == '-':
  print(n1-n2)
elif choice == '*':
  print(n1*n2)
elif choice == '/':
  print(n1/n2)

# Write a program that simulates a complex traffic light system with pedestrian
# crossing, emergency vehicle priority, and rush hour timing. %%

import time
from datetime import datetime

def get_current_hour():
    """Get current hour or simulate for testing"""
    # For testing, you can change this value
    current_time = datetime.now().hour
    return current_time

def is_rush_hour(hour):
    """Determine if current time is rush hour"""
    morning_rush = 7 <= hour <= 9
    evening_rush = 17 <= hour <= 19  # 5 PM to 7 PM
    return morning_rush or evening_rush

def is_night_time(hour):
    """Determine if it's night time"""
    return hour >= 22 or hour <= 5  # 10 PM to 5 AM

def get_traffic_timing(hour):
    """Get traffic light timing based on time of day"""
    if is_night_time(hour):
        return {
            'green': 15,
            'yellow': 3,
            'red': 15,
            'pedestrian_walk': 10
        }
    elif is_rush_hour(hour):
        return {
            'green': 60,     # Extended green during rush hour
            'yellow': 5,
            'red': 25,
            'pedestrian_walk': 20
        }
    else:
        return {
            'green': 30,
            'yellow': 5,
            'red': 25,
            'pedestrian_walk': 15
        }

def handle_emergency_override():
    """Handle emergency vehicle priority"""
    print("🚨 EMERGENCY VEHICLE DETECTED! 🚨")
    print("Immediately switching to GREEN for emergency vehicle")
    print("Emergency green light: 45 seconds")
    print("Emergency vehicle passed. Resuming normal cycle...")
    return True

def handle_pedestrian_crossing(timing):
    """Handle pedestrian crossing request"""
    print(f"\n👥 Pedestrian crossing activated")
    print(f"🚶 WALK signal: {timing['pedestrian_walk']} seconds")
    print("🚶 DON'T WALK (flashing): 5 seconds")
    print("Pedestrians can cross safely")

def display_traffic_state(state, duration, additional_info=""):
    """Display current traffic light state"""
    colors = {
        'green': '🟢 GREEN',
        'yellow': '🟡 YELLOW',
        'red': '🔴 RED'
    }
    print(f"{colors[state]} light: {duration} seconds {additional_info}")

def simulate_traffic_light():
    """Main traffic light simulation"""
    print("🚦 COMPLEX TRAFFIC LIGHT SYSTEM 🚦")
    print("=" * 50)

    # Get inputs
    current_hour = int(input("Enter current hour (0-23): "))

    print(f"\nCurrent time: {current_hour}:00")

    # Determine time-based conditions
    if is_night_time(current_hour):
        print("🌙 NIGHT MODE ACTIVATED")
        print("🔴 Blinking red lights - Stop and proceed when safe")
        return

    timing = get_traffic_timing(current_hour)

    if is_rush_hour(current_hour):
        print("🚗 RUSH HOUR MODE - Extended green timing")
    else:
        print("🕐 NORMAL HOURS - Standard timing")

    # Check for emergency vehicle
    emergency = input("\nIs emergency vehicle approaching? (yes/no): ").lower() == 'yes'

    if emergency:
        handle_emergency_override()
        print("\nResuming normal cycle after emergency...")

    # Check for pedestrian request
    pedestrian_request = input("Pedestrian crossing button pressed? (yes/no): ").lower() == 'yes'

    print("\n" + "="*50)
    print("TRAFFIC LIGHT CYCLE:")
    print("="*50)

    # Normal traffic cycle
    print(f"\n🚦 Current timing pattern:")
    display_traffic_state('green', timing['green'])

    if pedestrian_request:
        print("⏳ Pedestrian request noted - will activate after vehicle green phase")

    display_traffic_state('yellow', timing['yellow'], "(Prepare to stop)")
    display_traffic_state('red', timing['red'])

    # Handle pedestrian crossing during red phase
    if pedestrian_request:
        handle_pedestrian_crossing(timing)

    print(f"\n📊 CYCLE SUMMARY:")
    print(f"Total cycle time: {timing['green'] + timing['yellow'] + timing['red']} seconds")
    print(f"Time of day: {'Rush Hour' if is_rush_hour(current_hour) else 'Normal Hours'}")
    print(f"Emergency override: {'Yes' if emergency else 'No'}")
    print(f"Pedestrian crossing: {'Activated' if pedestrian_request else 'Not requested'}")

def advanced_scenario_demo():
    """Demonstrate complex scenarios"""
    print("\n" + "="*60)
    print("🎯 ADVANCED SCENARIOS DEMONSTRATION")
    print("="*60)

    scenarios = [
        {
            'hour': 8, 'emergency': True, 'pedestrian': True,
            'description': 'Rush Hour + Emergency + Pedestrian'
        },
        {
            'hour': 14, 'emergency': False, 'pedestrian': True,
            'description': 'Normal Hours + Pedestrian Only'
        },
        {
            'hour': 23, 'emergency': False, 'pedestrian': False,
            'description': 'Night Time Mode'
        }
    ]

    for i, scenario in enumerate(scenarios, 1):
        print(f"\n--- SCENARIO {i}: {scenario['description']} ---")
        hour = scenario['hour']

        if is_night_time(hour):
            print("🌙 Night mode: Blinking red lights")
            continue

        timing = get_traffic_timing(hour)

        if scenario['emergency']:
            print("🚨 Emergency vehicle priority activated!")
            print("⚡ Immediate green: 45 seconds")

        print(f"🟢 Green: {timing['green']}s")
        print(f"🟡 Yellow: {timing['yellow']}s")
        print(f"🔴 Red: {timing['red']}s")

        if scenario['pedestrian']:
            print(f"🚶 Pedestrian walk: {timing['pedestrian_walk']}s")

# Run the simulation
if __name__ == "__main__":
    try:
        simulate_traffic_light()

        demo = input("\nWould you like to see advanced scenarios demo? (yes/no): ")
        if demo.lower() == 'yes':
            advanced_scenario_demo()

    except ValueError:
        print("❌ Please enter valid numeric values!")
    except KeyboardInterrupt:
        print("\n\n🛑 Traffic light system stopped!")

Credit_Score = int(input("Enter your Credit_Score"))
Annual_Income = int(input("Enter your Annual_Income"))
Current_Monthly_Debt = int(input("Enter your Current_Monthly_Debt"))
Years_at_Current_Job = int(input("Enter your Years_at_Current_Job"))
Employment_Type = input("Enter your Employment_Type")
Collateral_Value = int(input("Enter your Collateral_Value"))
Loan_Amount_Requested = int(input("Enter your Loan_Amount_Requested"))

Debt_to_Income_Ratio = (Current_Monthly_Debt / Annual_Income) * 100
Monthly_Income = Annual_Income / 12
print("Monthly_Income")
print("Debt_to_Income_Ratio")
# Strong Approval
if Credit_Score >= 700 and Annual_Income >= 3*Loan_Amount_Requested and Years_at_Current_job >= 2 and Collateral_Value >= 0.5*Loan_Amount_Requested:
  print("Strong Approval")
elif:
  if Credit_Score >= 650 and Credit_Score >= 699 and Debt_to_Income_Ratio > 30 and debt_to_Income_ratio < 40:
    print("Conditional Approval : Reduce loan amount by 25% OR provide co-signer")
  elif Credit_Score >= 700 and Debt_to_Income_Ratio > 30 and Years_at_Current_Job < 2:
    print("Higher interest rate (+2%) AND/OR co-signer required")
  elif Credit_Score > 600 and Credit_Score < 649 and Monthly_Income > 4*Loan_Amount_Requested:
    print("Approve 75% of requested amount at higher interest rate")
  else:
    print("Approve 50% of requested amount, require co-signer, higher rate")
elif Credit_Score < 500 and Debt_to_Income_Ratio > 50 and Years_at_Current_Job > 1:
    print("Reject")

"""## DAY 9 — Python Loops: for, while, break, continue, pass

# While :- syntax
While condition:

## There is biggest problem in While is that you can not understand that what to put as condition in While loop and you do not know the loop will run infinite or not ?

## The Golden Rule of while Loops

## A while loop is safe only if the condition-controlling variable is guaranteed to change inside the loop.
"""

#Example 1 — Infinite Loop (Classic Mistake)
x = 5

while x > 0:
    print(x)

#Reason it out

#Condition depends on: x

#Does x change inside the loop? ❌ No

#Result: Infinite loop

##  Fix
while x > 0:
    print(x)
    x -= 1

# Example 3 — User Input Loop (Your Key Use Case)
user_input = input("Enter something: ")

while user_input != "quit":
    print("You typed:", user_input)

#Reason it out

#Condition variable: user_input

#Is it updated inside the loop? ❌ No

#Result: Infinite loop

#Correct version
while True:
    user_input = input("Enter something: ")

    if user_input == "quit":
        break

    print("You typed:", user_input)

for i in range(1,21):
  if i % 2 == 0:
    print(i)

# Ask the user for a number n and find the sum of numbers from 1 to n using a loop.

number = int(input("Enter a number :"))
sum = 0

i = 1
while i <= number:
  sum = sum + i
  i += 1
print(sum)

# find multiple of 3
n = int(input("Enter a number :"))
mul = 1

for i in range(1,11):
  mul = mul * i
  i = i + 1

# Ask the user for a number and print its multiplication table up to 10.

number = int(input("Enter a number: "))
for i in range(1, 11):
  print(f"{number} x {i} = {number * i}")

#Print numbers from 1 to 30, but skip multiples of 3 using continue.
i = 0

while i <= 30:
  if i % 3 == 0:
    i += 1
    continue
  print(i)
  i += 1

# Ask user for a number n and calculate its factorial using a for loop.

n = int(input("Enter a non-negative integer: "))
factorial = 1

if n < 0:
    print("Factorial is not defined for negative numbers.")
elif n == 0:
    print("The factorial of 0 is 1.")
else:
    for i in range(1, n + 1):
        factorial *= i
    print(f"The factorial of {n} is {factorial}")

#ou have a secret number 7.Keep asking the user to guess it using a while loop.
#If they guess correctly, print “Correct!” and stop.If they enter -1, print “Game Over!” and stop.Otherwise, ask again.

secret_number = 7
guess = None

while guess != secret_number:
    try:
        guess = int(input("Guess the secret number: "))
        if guess == secret_number:
            print("Correct!")
        elif guess == -1:
            print("Game Over!")
            break
        else:
            print("Try again.")
    except ValueError:
        print("Invalid input. Please enter an integer.")

# Take an integer input and reverse its digits using a loop.

num = int(input("Enter an integer: "))
reversed_num = 0

while num > 0:
    digit = num % 10  # Get the last digit
    reversed_num = reversed_num * 10 + digit # Add the digit to the reversed number
    num = num // 10  # Remove the last digit

print("Reversed number:", reversed_num)

#Ask user for a string, and count how many vowels it has (a, e, i, o, u).

string = input("Enter the string:")
sum= 0

for i in string:
  if i.lower() in 'aeiou':
    sum = sum + 1
print(sum)

for i in range(1,51):
  for j in range(2,i):
    if i%j == 0:
      break
  else:
    print(i)

"""## Day 10: Functions (basics) - def, arguments, return values"""

def say_hello():
    print("Hello!")

say_hello()

def greet(name):
    print("Hello", name)

greet("Riya")
greet("Alex")

"""name is a parameter (used inside the function)

"Riya" is an argument (value we pass while calling)

## practice questions
"""

def greet():
  print("Hello, Python Learner!")

greet()

#Write a function square(num) that returns the square of a number.

def square(num):
  print(num**2)

square(5)

def is_even(n):
  if n % 2 == 0:
    return True
  return False

is_even(66)

def is_sum(a,b):
  return (a+b)

is_sum(5,6)

def welcome(name):
  return (f"Welcome {name}")

welcome("Riya")

def isvowel(s):
  count = 0
  for i in s:
    if i.lower() in 'aeiou':
      count += 1
  return count

isvowel("hello")

def reverse(s):
  return s[::-1]

reverse("Riya")

#Write a function find_max(a, b, c) that returns the largest of 3 numbers.
def find_max(a,b,c):
  return max(a,b,c)

#Write a function factorial(n) that returns n! (without using math library).

def factori

def count_even(numbers):
  count = 0
  for i in numbers:
    if i % 2 == 0:
      count += 1
  return count

count_even([1,2,3,4,6])

"""## Day 11: Functions (advanced) - *args, **kwargs, lambda, scope

1. *args — Variable-Length Positional Arguments
What is *args?

Allows a function to accept any number of positional arguments.

Inside the function, args behaves like a tuple.

Why do we use it?

When we do not know how many values a user will pass.

To write flexible, reusable functions.
"""

def function_name(*args):
    # args is a tuple

def add_all(*args):
    return sum(args)

print(add_all(1, 2))          # 3
print(add_all(1, 2, 3, 4))    # 10

"""2. **kwargs — Variable-Length Keyword Arguments
What is **kwargs?

Accepts any number of keyword arguments (like key=value pairs).

Inside the function, kwargs behaves like a dictionary.

Why do we use it?

To accept flexible parameters (like configuration options).

Useful for functions where different users want different settings.
"""

def function_name(**kwargs):
    # kwargs is a dictionary

def print_details(**kwargs):
    for key, value in kwargs.items():
        print(f"{key}: {value}")

print_details(name="Riya", age=23, country="Canada")

def demo(a, b, *args, **kwargs):
    print(a, b)
    print(args)
    print(kwargs)

demo(1, 2, 3, 4, x=10, y=20)

"""What is a lambda?

A small one-line function with no name.

Used when a simple function is needed for a short time.

## lambda arguments: expression

## map(function, iterable)
Takes a function

Applies it to every element of the iterable

Returns a map object (convert to list if needed)
"""

##  Lambda with map()
nums = [1, 2, 3]
doubled = list(map(lambda x: x*2, nums))
print(doubled)  # [2, 4, 6]

"""## filter(function, iterable)
Takes a function that returns True or False

Keeps only the elements for which the function returns True

How filter() Works
It filters elements from a list/tuple based on a condition.


"""

## Lambda with filter()
nums = [1, 2, 3, 4, 5]
even = list(filter(lambda x: x % 2 == 0, nums))
print(even)

"""## Day 12 : Recursion

A recursive function is a function that calls itself until it reaches a stopping condition (base case).

Recursion = a function that solves a big problem by solving smaller parts of the same problem.

A recursive function must have two things:

        1.Base Case — a stopping rule.

        2.Recursive Call — the function calls itself.



"""

## Example
# simple countdown

def count(n):
  if n == 0:
    print('Blastoff')
    return
  print(n)
  count(n-1)

count(5)

# factorial

def factorial(n):
  if n==0 or n==1:
    return 1
  return n*factorial(n-1)


factorial(4)

def fibonacci(n):
    if n <= 1:
        return n
    return fibonacci(n-1) + fibonacci(n-2)

fibonacci(4)

# 1
def number(n):
  if n== 0:
    return
  number(n-1)
  print(n)

number(5)

def factorial(n):
  if n==0 or n==1:
    return 1
  return n * factorial(n-1)

factorial(4)

def sum(n):
  if n==0:
    return 0
  return n + sum(n-1)

sum(4)

def sum_n(n):
    if n == 0:
        return 0
    return n + sum_n(n - 1)

sum_n(5)

# Sum of Digits

#Input: 987 → Output: 24


def number(n):
  if n==0:
    return 0
  return (n%10) + number(n//10)

number(987)

# Handle Division by Zero

#Ask user for two numbers and safely divide them.

n1 = input("Enter the first number: ")
n2 = input("Enter the second number: ")

try:
    n1 = int(n1)
    n2 = int(n2)
    result = n1 / n2
    print("Result:", result)

except ValueError:
    print("Invalid input. Please enter numbers only.")

except ZeroDivisionError:
    print("Cannot divide by zero.")

def sum_n(number):
  count = 0
  result = set(sum(number))
  return result

print(sum_n([1,2,2]))

"""## Day 16: List Comprehensions & Generators - Generator expressions, yield


"""



"""## Day 19: OOP (Classes & Objects) - __init__, attributes, methods
## Day 20: OOP (Inheritance & Polymorphism) - super(), overriding
## Day 21: OOP (Dunder Methods) - __str__, __len__, etc

Q : what is Class ?
A : A class is a blueprint or template that defines the properties and behaviors of an object.

Q2 : What is an Object?
A2 : An object is a real instance of a class that occupies memory and can use the class’s attributes and methods.

Q3 : What is an Instance?
A3 : An instance is a specific object created from a class, with its own state stored in memory.

Q4 : What is __init__?
A4 : __init__ is a constructor method that initializes an object’s attributes when the object is created.

Q5 : What is self?
A5 : self refers to the current instance of the class and is used to access instance variables and methods.
"""

class Car:
  # constructor
  def __init__(self,windows, tyres, engine):
    self.windows = windows
    self.tyres = tyres
    self.engine = engine

  def self_driving(self,engine):
    print("the car engine is {}".format(engine))

car1 = Car(4,4,"petrol")
print("The number of tyres in Car is {}".format(car1.tyres))
print("The number of windows in Car is {}".format(car1.windows))
car1.self_driving("petrol")

"""## Interview Question :
# Q : does multiple __init__ constructors allowed in python ?
# A : Python does not support multiple constructors directly because it allows only one __init__ method. However, we can simulate multiple constructors using default arguments, conditional logic, or more cleanly using class methods, which is the preferred and Pythonic approach.
"""

class Animal():
  def __init__(self,name,age):
    self.name = name
    self.age = age

  def __init__(self,name,age,typ):
    self.name = name
    self.age = age
    self.typ = typ

  def make_sound(self,sound):
    print(f"{self.name} says {sound}")

dog = Animal("Buddy",10)
print(dog)

"""## see in above code the first constructor is not working. it is directly working on second constructor."""

class Animal:
    def __init__(self,*args):
        if len(args)==1:
            self.name = args[0]
        elif len(args)==2:
            self.name = args[0]
            self.species = args[1]
        elif len(args)==3:
            self.name = args[0]
            self.species = args[1]
            self.age = args[2]

    def make_sound(self, sound):
        return "The animal is {} and says {}".format(self.name, sound)

dog=Animal("dog","mammals",17)
print(dog.name)
print(dog.species)
print(dog.age)
print(dog.make_sound("woof wwoof"))

"""## Inheritence

"""

class Car:
  def __init__(self,windows,tyres,engine):
    self.windows = windows
    self.tyres = tyres
    self.engine = engine

  def self_driving():
    print("It is a self-driving car.")

class Audi(Car):
  def __init__(self,windows,tyres,engine,speed):
    super().__init__(windows,tyres,engine)
    self.speed = speed


audi = Car(4,4,"petrol")
print(audi.windows)
print(audi.tyres)
print(audi.engine)

"""## What is purpose of super() ?
## A:  super() is used to call methods or constructors of the parent class from a child class, ensuring proper initialization and reuse of parent functionality.

## why is inheritence important ?
## A: Inheritance is important because it allows code reusability, reduces duplication, and enables hierarchical relationships between classes, making systems easier to maintain and extend.

## Encapsulation In Python
Encapsulation is a fundamental principle in object-oriented programming that focuses on bundling data and the methods that operate on that data into a single unit called a class. It allows you to control the access and visibility of the data and methods, providing a way to protect and organize your code
"""

### Access Modifier--->Encapsulation
## private

class Person:
  def __init__(self,name,age):
    self.__name = name
    self.__age = age

  def display_info(self):
        print(f"the person name is {self.__name} and the age is {self.__age}")

person=Person("Krish",32)

person.display_info()

### Access Modifier--->Encapsulation
## Protected

class Person:
  def __init__(self,name,age):
    self._name = name
    self._age = age

person=Person("Krish",32)

dir(person)
person._age

class Student(Person):
    def __init__(self,name,age):
        super().__init__(name,age)

    def display_info(self):
        print(f"the person name is {self._name} and the age is {self._age}")

student1=Student("Krish",33)

student1.display_info()

"""## Private will only be used in class. If it is protected then only used in derived class. And public will be used anywhere.

## Polymorphism ->> Polymorphism means the ability of the same method name or operation to behave differently based on the object or context.
"""

class Phone:
  def __init__(self,brand,model):
    self.brand = brand
    self.model = model
  def buy(self):
    print("Buying a phone.")

class Smartphone(Phone):
  def buy(self):
    print("Buying a smartphone.")

s = Smartphone("Samsung","S21")
s.buy()

"""## Python DataClasses

In Python, the dataclass decorator is a feature introduced in Python 3.7 that provides a concise way to define classes primarily intended to store data. It automatically generates several special methods, such as init, repr, and eq, based on the class attributes you define. This simplifies the process of creating and working with data-focused classes.
"""

from dataclasses import dataclass

@dataclass
class Person:
  name: str
  age: int
  profession:str

"""# The @dataclass decorator automatically generates the following methods for you:

1.init(): Initializes the object and assigns the provided values to the attributes.
2.repr(): Provides a string representation of the object.
3.eq(): Implements equality comparison between two objects of the class based on their attributes.
"""

person1=Person('Krish',17,'SE')
person1

person1.age

@dataclass
class Rectangle:
    width:int
    height:int
    color:str='white'

rectangle1=Rectangle(12,14)
rectangle2=Rectangle(13,14,'red')

"""## like class you can chane the value of specific value."""

rectangle2.color

@dataclass(frozen=True)
class Point:
    x:int
    y:int

point=Point(3,4)

point.x=12

## inheritance

@dataclass
class Person:
    name:str
    age:int

@dataclass
class Employee(Person):
    employee_id:str
    department:str

person=Person('Krish',31)
employee=Employee("KRish",31,'123','AI')

employee.name

from dataclasses import dataclass
@dataclass
class Address:
    street:str
    city:str
    zip_code:str

@dataclass
class Person:
    name:str
    age:str
    address:Address

address=Address('123 MAin street','Bangalore','12345')
person=Person("Krish",31,address)

person.address.city

"""## Re - Regular expression

# What is Regular Expression ?
# A regular expression is a pattern used to search, match, and manipulate text.


"""





"""## Practicepython Practice questions"""

a = [1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89]
b = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]

#write a program that returns a list that contains only the elements that are common between the lists
#(without duplicates). Make sure your program works on two lists of different sizes.

result = []
for i in a:
  if i in b:
    result.append(i)
print(set(result))

a = [1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89]
b = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
print(set(a[x] for x in range(len(a))if a[x] in b))

s = input("Enter a string: ")

def palindrom(s):
  if s == s[::-1]:
    print("The string is a palindrome.")
  else:
    print("The string is not a palindrome.")

palindrom(s)

a = [1, 4, 9, 16, 25, 36, 49, 64, 81, 100]
#Write one line of Python that takes this list a and makes a new list that has only the even elements of this list in it.

lst = [i for i in a if i%2 == 0]
print(lst)

## Rock paper & Scissor game
import random

given_choice = ['Rock','Paper','Scissor']
user_choice = input("Enter your choice (Rock, Paper, Scissor): ")
computer_choice = random.choice(given_choice)

while user_choice != 'quit':
  if user_choice == 'quit':
    break
  elif user_choice == computer_choice:
    print("It's a tie!")
  elif user_choice == 'Rock' and computer_choice == 'Scissor':
    print("You win!")
  elif user_choice == 'Scissor' and computer_choice == 'Paper':
    print("You win!")
  elif user_choice == 'Paper' and computer_choice == 'Rock':
    print("You win!")
  else:
    print("You lose!")

while True:
    user_input = input("Enter something: ")

    if user_input == "quit":
        break

    print("You typed:", user_input)

























